# Name of our action
name: Release

# The event that will trigger the action
on: push

# what the action will do
jobs:
  release:
    # The operating system it will run on
    runs-on: ubuntu-latest

    # This check needs to be in place to prevent a publish loop with auto and github actions
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.GH_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      HUSKY: 0

    # The list of steps that the action will go through
    steps:
      # Checks-out your repo so your workflow can access it.
      - uses: actions/checkout@v2

      # Fetch repo with tags, converting from shallow to complete
      - name: Prepare repository
        run: git fetch --unshallow --tags

      # Download Node and configure for GitHub Packages
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@bamerf'

      # Cache dependencies and build outputs to improve workflow execution time
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Check types
      - name: Check types
        run: yarn types:check

      # Build a package
      - name: Build
        run: yarn package:build

      # Finalise build
      - name: Postbuild
        run: yarn package:postbuild

      - name: Log build files
        run: |
          ls -al ./dist/

      # Release
      - name: Release
        run: yarn package:release
